Feature/extend api
GAIA-X4PLC-AAD/self-description-creator pull request #5
Opened 2024-01-17 09:13 UTC by JustinDxx

Extended the application by adding three new endpoints:

**/sd-from-vp-without-proof:**
input: a Verifiable Presentation without proof
output: a Verifiable Presentation having a proof (=SD)

**/vc-from-claims**
input: claims about an object
output: a Verifiable Credential

**/sd-from-vcs**
input: a list of Verifiable Credentials
output: a Verifiable Presentation (=SD)

2024-01-22 16:18 UTC, robertschubert requested changes
Review durchgeführt, Anmerkungen im PR.

2024-01-22 16:18 UTC, robertschubert commented on openapi-spec.yaml
> +  /sd-from-vp-without-proof:
siehe Anmerkungen in der Postman collection

2024-01-22 16:18 UTC, robertschubert commented on src/self_description_creator.py
> +signature_jwk: JWK = None # type: ignore
wieso braucht es diesen neuen Kommentar?

2024-01-22 16:18 UTC, robertschubert commented on src/self_description_creator.py
> +        self_description = self_description_processor._add_proof(credential=vp_without_proof) # type: ignore
hier würde ich "_add_proof" zu "add_proof" ändern. Das _ soll wohl ein private suggerieren, wir rufen es jetzt aber von außen auf.

2024-01-22 16:18 UTC, robertschubert commented on src/self_description_creator.py
> +        self_description = self_description_processor.create_self_description(claims=claims) # type: ignore
auch hier gibt es diesen Kommentar am Ende. Brauchst du das für's linting?

2024-01-22 16:18 UTC, robertschubert commented on openapi-spec.yaml
> +                  {
Hier scheint mir die Einrückung nicht zu passen:
der type mit der "VerifiableCredential" weiter unten ist weiter links.

2024-01-22 16:18 UTC, robertschubert commented on openapi-spec.yaml
> +              }
Hier ist der Grund für das Einrückungsproblem: } und ] sind auf gleicher Höhe

2024-01-22 16:18 UTC, robertschubert commented on openapi-spec.yaml
>              application/json:
kannst du nachschauen, ob wir die OpenAPI-Def im SD-Creator exposen über einen Endpoint?

2024-02-01 08:45 UTC, JustinDxx commented on SD Creator.postman_collection.json
> +			"name": "Create Self Description from Claims",
Müssen wir das in der Postman Collection ändern? Ich hätte das eher in dem Pythonskript angepasst, oder nicht? Hier wurde ja auch kein Endpoint geändert, sondern nur der Name, der in Postman angezeigt wird.

2024-02-02 08:55 UTC, JustinDxx commented on src/self_description_creator.py
> +        self_description = self_description_processor.create_self_description(claims=claims) # type: ignore
Ja, genau. Meistens tritt ein Error-Hinweis auf, dass nicht für "None" gecheckt wird. Wenn das Programm allerdings läuft und der Wert nicht None ist, gibt es keine Probleme. Das habe ich jetzt aber eingebaut, an einer Stelle ging es nicht ohne den Code deutlich zu verkomplizieren, dort habe ich einen Kommentar eingefügt.

2024-02-02 08:56 UTC, JustinDxx commented on openapi-spec.yaml
>              application/json:
Wir exposen sie jetzt, allerdings fehlen noch 1-2 Dinge, um die Doku auch sinnvoll nutzen zu können, da müssen wir mal absprechen, wie dringlich das ist.

2024-02-08 15:24 UTC, robertschubert commented on SD Creator.postman_collection.json
> +			"name": "Create Self Description from Claims",
python auf alle Fälle, da haben wir ja auch den redirect auf den neuen endpoint.
Hintergrund dafür, dass wir es in der postman collection schreiben ist, dass die Leute dazu übergehen, direkt den neuen Endpoint zu nutzen.

2024-02-08 15:26 UTC, robertschubert commented on openapi-spec.yaml
>              application/json:
Was du vielleicht noch oben in die Beschreibung einfügen könntest, ist dass "try it out" aktuell nicht funktioniert.
Eilt aber nicht und wir können das nachziehen.
Ich resolve die Konversation und lege einen TAsk an.

2024-02-08 16:13 UTC, robertschubert approved these changes
change approved, ready to merge

2024-02-29 13:03 UTC, merged