Feature/didstore
GAIA-X4PLC-AAD/self-description-creator pull request #6
Opened 2024-01-31 11:34 UTC by JustinDxx

Implement a feature to save the sent claims/VCs/VPs into a DID_Storage and to set the ID in the resulting document to the regarding endpoint.

2024-02-09 13:00 UTC, robertschubert requested changes
Review durchgeführt, Anmerkungen im PR.

2024-02-15 13:14 UTC, JustinDxx commented on src/self_description_creator.py
> +def return_id_documents():
openAPI ist angepasst, Postman würde ich nach dem Merge ergänzen wollen, um neue Konflikte zu vermeiden. Die extrahiere ich nämlich immer aus Postman direkt und dort gibt es natürlich keine Branches, weshalb die Collection auf dem anderen Pull Request basiert.

2024-02-15 13:15 UTC, JustinDxx commented on src/self_description_creator.py
> +                data[did_object.get_uuid()] = did_object.get_object_content()
Ist angepasst auf max. 500 UUIDs ohne Content. Ist sowieso sinnvoll, den Content kann man sich ja per UUID dann holen.

2024-02-15 13:58 UTC, JustinDxx commented on src/did_store.py
> +            raise Exception("Storage Type for DIDStore is not supported.")
Habe mir aufgrund deiner Anmerkungen pylint runtergeladen und würde die noch offenen Meldungen dann separat bearbeiten

2024-02-15 14:11 UTC, JustinDxx commented on src/self_description_processor.py
> +            did_store_object = self.__did_store.create_did_store_object(credential)
Den ersten Punkt verstehe ich nicht. 
Zum zweiten Punkt: Es kann keine ID existieren, weil wir das Dokument ja erst im SD Creator erzeugen. Also, wenn wir z. B. Claims bekommen, kann ja das VC keine ID haben. Die ID des Claims bleibt ja sowieso gleich.

2024-02-15 14:15 UTC, JustinDxx commented on src/did_store.py
> +            raise Exception("No filepath specified")
Habe ich so implementiert, habe aber noch eine Rückfrage dazu.

2024-02-29 13:38 UTC, robertschubert commented
@JustinDxx 
schau mal meinen letzten Kommentar an. Danach kannst Du die Mergekonflikte auflösen (gib Bescheid, wenn Du da Hilfe brauchst. Ich kann Dir zeigen, wie das geht).

2024-03-01 14:34 UTC, JustinDxx commented
Habe die Merge Conflicts jetzt resolvet, jetzt sollte alles passen.

2024-03-11 09:14 UTC, merged