Feature/refactoring
GAIA-X4PLC-AAD/self-description-creator pull request #8
Opened 2024-03-12 10:36 UTC by JustinDxx

Refactored the code and removed unused helm repository.

2024-03-14 15:25 UTC, JustinDxx commented
included change of endpoint for /id-documents due to did-web-resolution

2024-03-14 16:19 UTC, robertschubert requested changes
approved.

2024-03-14 16:19 UTC, robertschubert commented on src/self_description_creator.py
> +@app.route("/id-documents/<request_uuid>/did.json", methods=["GET"])
Hier braucht es noch eine Anpassung der OpenAPI und der postman collection

2024-03-22 12:09 UTC, robertschubert approved these changes
approved

2024-03-22 12:10 UTC, merged